// subset of @material-ui/icons and @amsterdam/asc-assets, only the icons used in the app
// if the preferred icon is not in this list you can add it by im/export it from @material-ui/icons
// https://material.io/resources/icons/

export { default as AssignmentTurnedIn } from "@material-ui/icons/AssignmentTurnedInOutlined"
export { default as Check } from "@material-ui/icons/Check"
export { default as ChevronRight } from "@material-ui/icons/ChevronRight"
export { default as Close } from "@material-ui/icons/Close"
export { default as Delete } from "@material-ui/icons/DeleteOutline"
export { default as Edit } from "@material-ui/icons/EditOutlined"
export { default as Euro } from "@material-ui/icons/Euro"
export { default as ExpandLess } from "@material-ui/icons/ExpandLess"
export { default as ExpandMore } from "@material-ui/icons/ExpandMore"
export { default as Folder } from "@material-ui/icons/FolderOutlined"
export { default as Help } from "@material-ui/icons/HelpOutline"
export { default as Home } from "@material-ui/icons/HomeOutlined"
export { default as Info } from "@material-ui/icons/InfoOutlined"
export { default as Lock } from "@material-ui/icons/Lock"
export { default as Logout } from "@amsterdam/asc-assets/lib/icons/Logout"
export { default as Portrait } from "@material-ui/icons/PortraitOutlined"
export { default as PermIdentity } from "@material-ui/icons/PermIdentity"
export { default as Refresh } from "@material-ui/icons/Refresh"
export { default as Search } from "@material-ui/icons/Search"
export { default as ArrowUpward } from "@material-ui/icons/ArrowUpward"
export { default as ArrowDownward } from "@material-ui/icons/ArrowDownward"
export { default as VerifiedUser } from "@material-ui/icons/VerifiedUser"
export { default as PanTool } from "@material-ui/icons/PanTool"
export { default as CloudUpload } from "@material-ui/icons/CloudUpload"
export { default as Pageview } from "@material-ui/icons/PageviewOutlined"
