export default [
  {
    label: "Wat is de situatie?",
    type: "text",
    camunda_type: "String",
    name: "situation",
    default_value: "",
    required: true,
    is_date: false,
    options: [],
    tooltip: null,
  },
  {
    label: "Kan volgende bezoek doorgaan?",
    type: "checkbox",
    camunda_type: "Boolean",
    name: "can_next_visit_go_ahead",
    default_value: "",
    required: true,
    is_date: false,
    options: [],
    tooltip: null,
  },
  {
    label: "LABEL 0",
    type: "select",
    camunda_type: "Boolean",
    name: "FormField_3qjm0em",
    default_value: null,
    required: true,
    is_date: false,
    options: [
      { label: "test", value: "Value_0iaq2tn" },
      { label: "asffassfa", value: "Value_0qd0jvv" },
    ],
    tooltip: null,
  },
  {
    label: "LABEL 1",
    type: "text",
    camunda_type: "String",
    name: "FormField_3vj52a2",
    default_value: "",
    required: true,
    is_date: true,
    options: [],
    tooltip: null,
  },
  {
    label: "LABEL 3",
    type: "text",
    camunda_type: "Long",
    name: "FormField_0cgfa15",
    default_value: "",
    required: true,
    is_date: false,
    options: [],
    tooltip: null,
  },
];
