name: 'Install, lint, test, E2E & build'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          env: true
          build: npm run build
          start: npm start
          wait-on: "http://localhost:2999/"
        env:
          CYPRESS_TEST_USER_PASSWORD:  ${{ secrets.CYPRESS_TEST_USER_PASSWORD }}

      - name: Build
        run: docker build .
