name: 'Install, lint, test, E2E & build'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test

      - name: Cypress run
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: cypress-io/github-action@v4
        with:
          record: false
          # Run test against acc, otherwise a local backend is needed.
          start: npm run acc
          wait-on: "http://localhost:2999/"
        env:
          # pass GitHub token to allow accurately detecting a build vs a re-run build for Cypress Dashboard
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # pass the Dashboard record key as an environment variable for Cypress Dashboard
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_TEST_USER_PASSWORD:  ${{ secrets.CYPRESS_TEST_USER_PASSWORD }}

      - name: Build
        run: docker build .
