# action.yml
name: 'Lint, test & build'
on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout frontend
        uses: actions/checkout@v2
        with:
          path: frontend

      - name: Checkout backend
        uses: actions/checkout@v2
        with:
          repository: amsterdam/zaken-backend
          path: backend

      - name: Start backend
        run: frontend/.github/workflows/on-pull-request/start-backend.sh

      - name: Sleep for 2m
        uses: jakejarvis/wait-action@master
        with:
          time: '2m'

      - name: Check running containers
        run: docker ps -a

      - name: Run tests
        run: frontend/.github/workflows/on-pull-request/test.sh
